/* Nocta — doctor summary. The doctor path: a hard-escalation why-card opens
 * this instead of suggesting a self-fix. It shows what made Nocta suggest it
 * (the insight's own cited numbers, no interpretation) and what goes into the
 * one-page PDF. Per FEATURES › Doctor PDF export, the PDF carries numbers only
 * — no AI commentary. Mock export: idle → preparing → ready. */
import { useState } from 'react';
import { useStore } from '../lib/store.jsx';
import { FIXTURES } from '../data/fixtures.js';
import { NIGHTS_ON_THERAPY } from '../data/history.js';
import { Sheet } from '../components/Sheet.jsx';
import { Icon } from '../components/Icons.jsx';

const CONTENTS = [
  'AHI for each night, with the trend',
  'Central, obstructive and hypopnea counts',
  'Mask leak over time',
  'Pressure range your machine used',
  'Hours of use each night',
];

function fmt(c) {
  const unit = c.unit === 'events/hr' ? ' an hour' : c.unit === 'count' ? '' : ` ${c.unit}`;
  return `${c.value}${unit}`;
}

export function DoctorSummarySheet() {
  const { closeSheet, fixtureId, showToast } = useStore();
  const fx = FIXTURES[fixtureId];
  const [state, setState] = useState('idle');

  const reasons = fx.insight.data_citations.map((c) => ({ k: c.metric, v: fmt(c) }));
  const spo2 = fx.bodyResponse?.spo2;
  if (spo2?.flag) reasons.push({ k: 'Lowest blood oxygen', v: `${spo2.low}%` });

  function prepare() {
    if (state !== 'idle') return;
    setState('preparing');
    setTimeout(() => {
      setState('ready');
      showToast('Doctor summary ready', 'download');
    }, 1400);
  }

  return (
    <Sheet
      eyebrow="For your doctor"
      title="Doctor summary"
      onClose={closeSheet}
      footer={(close) =>
        state === 'ready' ? (
          <button className="btn primary" onClick={close}>
            Done
          </button>
        ) : (
          <button className="btn primary" onClick={prepare} disabled={state === 'preparing'} aria-busy={state === 'preparing'}>
            {state === 'preparing' ? 'Preparing your PDF…' : 'Prepare PDF'}
          </button>
        )
      }
    >
      <div className="doc-sheet">
        <p className="doc-lede">
          A one-page PDF of all {NIGHTS_ON_THERAPY} of your nights so far to bring to your next
          appointment. It shows your
          numbers only, with no Nocta commentary, so your doctor can read it their way.
        </p>

        <section className="doc-block" aria-labelledby="doc-why">
          <h4 id="doc-why">Why Nox suggested this</h4>
          <dl className="doc-reasons">
            {reasons.map((r) => (
              <div key={r.k}>
                <dt>{r.k}</dt>
                <dd className="tnum">{r.v}</dd>
              </div>
            ))}
          </dl>
          <p className="doc-note">
            This is a pattern for your sleep doctor to look at. Keep using your machine as
            prescribed and don't change your settings on your own.
          </p>
        </section>

        <section className="doc-block" aria-labelledby="doc-what">
          <h4 id="doc-what">What's in the PDF</h4>
          <ul className="doc-contents">
            {CONTENTS.map((c) => (
              <li key={c}>
                <Icon name="check" size={15} />
                {c}
              </li>
            ))}
          </ul>
        </section>

        {state === 'ready' && (
          <div className="doc-ready" role="status">
            <Icon name="doc" size={18} />
            <span>
              <strong>Summary ready.</strong> {NIGHTS_ON_THERAPY} nights, one page. Generated by Nocta from SleepHQ
              data. Not a medical record.
            </span>
          </div>
        )}
      </div>
    </Sheet>
  );
}
